opencobra/memote

.travis.yml, requirements.in, tox.ini
* build only master and PRs to master
* finish on first error
* remove redundant tox stuff
=> improve travis behavior

memote/suite/collect.py, memote/suite/conftest.py, memote/suite/report.py, memote/suite/runner.py, memote/suite/test_basic.py, memote/suite/test_consistency.py, requirements.in, requirements_dev.in, setup.py
Creates a local Plugin with a fixture that can be used to store data on.
=> Collection of data for reporting

memote/suite/test_syntax.py, memote/support/syntax.py, tests/test_for_support/test_for_syntax.py
As outlined [here](https://github.com/biosustain/memote/issues/5), this implements syntax rules outlined by Thiele & Palsson (2010). Ommissions are discussed in in the issue.
---------------------------------------------------------------------------------------------
Thiele, I., & Palsson, B. Ø. (2010, January). A protocol for generating a high-quality genome-scale metabolic reconstruction. Nature protocols. Nature Publishing Group. http://doi.org/10.1038/nprot.2009.203
=> Implement syntax protocol [fix #5]

memote/suite/tests/test_biomass.py, memote/support/biomass.py, memote/support/helpers.py, memote/support/syntax.py, requirements_dev.in, setup.py, tests/test_for_support/test_for_biomass.py, tox.ini
closes #30, closes #31, closes #32
=> Operational tests regarding the Biomass reaction.

memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
Cherry picking @ChristianLieven's commits for ATP production tests and imbalanced reactions. Adjusting functions to new cobra API.
=> Further stoichiometric consistency tests

memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
Changed the functions slightly to use the new cobra API and `pandas.DataFrame` indexing.
=> Test for blocked reactions [fix #37]

memote/suite/collect.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/suite/tests/test_syntax.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
Add the `store` fixture to all current model test cases. Plus other minor tweaks.
=> refactor: improve the number of results being stored

memote/suite/reporting/bag.py, memote/suite/reporting/plot.py, memote/suite/reporting/reports/history_report.py, memote/suite/reporting/templates/history_report.html, memote/suite/reporting/templates/layout.html
* Add axis titles to plots.
* Configure plotly with MathJax such that basic Latex is possible.
* Improve X axis layout (hashes and timestamps).
=> feat: plot axes with MathJax

memote/suite/tests/test_biomass.py, memote/support/biomass.py, tests/test_for_support/test_for_biomass.py
=> 64 test for ngam

memote/suite/tests/test_biomass.py, tests/test_for_support/test_for_biomass.py
resolves #38 
Please refer to the issue for more information. The added content is a straight-forward test of growth.
=> Check for growth that is too fast.

tests/test_for_support/test_for_annotation.py
=> refactor: Correct model_builder in annotation.py

memote/suite/reporting/bag.py, memote/suite/reporting/plot.py, memote/suite/reporting/reports/history_report.py, memote/suite/reporting/templates/_card_helpers.html, memote/suite/reporting/templates/history_report.html, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_syntax.py, memote/support/basic.py, memote/support/biomass.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_biomass.py
* Fix the toggle in the one-time report.
* Add more plots.
* Simplify templates a lot.
I had to leave large parts of the syntax and annotation tests. Our infrastructure is too brittle for now.
=> feat: add more plots to the history report

docs/conf.py, docs/organization.rst, docs/requirements.txt
Specify requirements for readthedocs.
=> refactor: organize documentation build

.travis.yml, Makefile, docs/requirements.txt, tox.ini
Testing docs should be expanded in future.
=> feat: make docs generation part of tox

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.rst, README.rst
* Add Gitter badge
* Fix contributing link
=> feat: improve GitHub support

.github/ISSUE_TEMPLATE.md, memote/__init__.py, memote/version_info.py
=> feat: give users easy access to dependency versions for smoother bug reports

HISTORY.rst, memote/suite/cli/callbacks.py, memote/suite/cli/config.py, memote/suite/cli/runner.py, setup.py
Add a new command `memote online` which creates a repository on GitHub if necessary, obtains a personal access token, links the repository with Travis CI, encrypts the token in the `.travis.yml` file, and pushes the changes.
=> feat: new command memote online

HISTORY.rst, memote/suite/tests/test_basic.py, memote/support/basic.py, memote/support/helpers.py, memote/support/syntax.py, setup.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_helpers.py, tests/test_for_support/test_for_syntax.py
=> More tests

memote/suite/tests/test_basic.py
Required for JSON serialization.
=> fix: store only reaction IDs

docs/getting_started.rst
Updated the docs to reflect the latest changes to the CLI
=> docs: update documentation to reflect changed CLI

HISTORY.rst, memote/support/consistency.py, memote/support/consistency_helpers.py
This may be the bug that caused the many reported inconsistent metabolites.
=> fix: exclude biomass reactions from internal ones

HISTORY.rst, memote/suite/tests/test_consistency.py, memote/support/consistency.py, memote/support/consistency_helpers.py, tests/test_for_support/test_for_consistency.py
* Split mass-charge-balance test into two separate tests for more clarity
=> Split mass charge

HISTORY.rst, memote/suite/tests/test_basic.py
=> fix: correct the assertion output

HISTORY.rst, memote/support/annotation.py
=> fix: remove the print statement

memote/suite/tests/test_annotation.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_consistency.py
=> fix: last minute fixes

memote/suite/api.py, memote/suite/cli/callbacks.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, memote/suite/tests/test_consistency.py, memote/support/basic.py, memote/support/consistency.py, memote/support/helpers.py, requirements_dev.in, tests/test_for_suite/test_for_cli/test_for_callbacks.py, tox.ini
=> fix: simplify callbacks and correct history output

memote/suite/cli/__init__.py, memote/suite/cli/callbacks.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, memote/suite/reporting/bag.py, memote/version_info.py, setup.py
Also fix some problems in the command line interface.
=> feat: introduce click-log to replace echo [fix #247]

.travis.yml, ci/travis/update_docker.sh, docs/requirements.txt, setup.cfg, setup.py
* Simplify the `.travis.yml`
* Parse and serialize bumpversion tags differently
* Make automated GitHub releases
* Auto-update opencobra/memote-docker on release
* Require at least newest cobra version
=> feat: improve the automated pipelines

memote/suite/cli/runner.py, memote/suite/collect.py, memote/suite/tests/test_annotation.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_consistency.py
Change the type of some of the tests.
=> fix: test output

memote/suite/test_config.yml
Extend the core test and report configuration.
=> refactor: first core tests draft

memote/suite/cli/__init__.py
* Quick fix to the GLPK model copy problem.
=> fix: do not use system locale but "C"

tests/test_for_support/test_for_biomass.py
See #291 comment: https://github.com/opencobra/memote/pull/291#issuecomment-355964087
=> fix: correct assertion after numpy update

HISTORY.rst, memote/suite/test_config.yml, memote/suite/tests/test_annotation.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/support/basic.py, memote/support/helpers.py, tests/test_for_support/test_for_basic.py
* x] description of feature/fix:
Updated all test docstrings (descriptions) to explain the tests better, the reasoning behind some of them and the conditions required to pass them.
=> Improve explanations

.travis.yml, HISTORY.rst, Makefile, memote-report-app/Makefile, memote-report-app/package-lock.json, tox.ini, tox_install.sh
Travis now creates the index.html with bundled/inlined javascript. Plus tox testing was made a bit simpler.
=> feat: let Travis bundle the JS

HISTORY.rst, memote/suite/tests/test_sbo.py, memote/support/sbo.py, tests/test_for_support/test_for_sbo.py
=> Implement dedicated SBO test module as outlined in #276

HISTORY.rst, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/support/consistency.py, memote/support/consistency_helpers.py, memote/support/helpers.py, tests/test_for_support/test_for_consistency.py, tests/test_for_support/test_for_helpers.py
This is a small PR implementing a test for Biomass production in complete medium, and fixing one minor oversight with the test that checks for mass- and charge-unbalanced reactions. I've updated the documentation for these tests too to make that change clear.
=> Add a test for Biomass production in complete medium 

HISTORY.rst, memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
* Correct the target to internal reactions not the number of all reactions.
=> fix: correct metric for imbalance tests

HISTORY.rst, memote/suite/collect.py, memote/suite/test_config.yml
=> feat: compute the total test score

.gitignore
=> chore: ignore new pytest cache directory

memote/suite/tests/test_biomass.py
=> fix: correctly handle metric dict in biomass

memote/suite/tests/test_sbo.py
* Fix a small mistake in getting the annotation dict from the right function object.
* Change the assertions to fail under the right conditions.
=> fix: correct the SBO test cases

memote/suite/tests/test_matrix.py
* Change the reported values around so that the report works properly.
=> refactor: change reporting of ratio test

HISTORY.rst, memote/suite/cli/runner.py, memote/suite/results/repo_result_manager.py
=> fix: correct the messed up arguments to storage

memote/suite/api.py, memote/suite/cli/reports.py, memote/suite/reporting/history.py, memote/suite/results/history_manager.py, memote/suite/results/repo_result_manager.py, memote/suite/results/sql_result_manager.py
=> fix: correctly handle result managers' arguments

HISTORY.rst, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py
=> fix: import division from __future__ in all test modules

HISTORY.rst, memote/suite/cli/reports.py
=> feat: add `skip` and `exclusive` options for the snapshot report

HISTORY.rst, memote/support/basic.py, memote/support/consistency_helpers.py, memote/support/helpers.py
=> Fixed Sidd's caching branch PR

memote-report-app/src/app/report-data.service.ts, memote-report-app/src/app/result-button/result-button.component.html, memote-report-app/src/app/test-history.model.ts, memote-report-app/src/app/test-result.model.ts, memote-report-app/src/app/vega-plot/vega-plot.component.ts, memote-report-app/src/data/testData.json, memote-report-app/src/data/testHistory.json
=> fix: rename type to format_type consistently

HISTORY.rst, memote/suite/api.py, memote/suite/cli/reports.py, memote/suite/reporting/history.py, memote/suite/reporting/report.py, memote/suite/reporting/snapshot.py, memote/suite/results/result_manager.py, memote/utils.py, tests/test_for_suite/test_for_api.py
Abstract some of the API work into the `jsonify` function in utils.
=> refactor: change APIs around

.travis.yml, tox.ini
=> refactor: improve codecov, stages

HISTORY.rst, memote/suite/api.py, memote/suite/cli/config.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, memote/suite/reporting/history.py, memote/suite/reporting/report.py, memote/suite/results/history_manager.py, memote/suite/results/repo_result_manager.py
=> refactor: optimize the history and report history

memote/suite/cli/runner.py
=> refactor: improve secure travis var

docs/experimental_data.rst, docs/getting_started.rst, docs/index.rst
=> docs: add description for experimental data

.travis.yml, HISTORY.rst, memote/experimental/config.py, memote/suite/reporting/config.py, setup.cfg, tox.ini
Fix #488 
Disable the docs testing on Travis in order to make a quick release.
=> fix: udpate ruamel.yaml

memote/suite/tests/test_thermodynamics.py, memote/support/thermodynamics.py, setup.cfg, tests/test_for_support/test_for_thermodynamics.py
=> fix: require Python 3.5+ for thermo tests

HISTORY.rst, memote/suite/reporting/report.py, tests/test_for_suite/test_for_reporting/test_for_history.py
=> fix: calculate section and total scores as expected and test it.

memote/experimental/config.py, memote/experimental/essentiality.py, memote/experimental/experimental_base.py, memote/experimental/growth.py, memote/experimental/tabular.py
=> fix: correct medium and experiment loading

HISTORY.rst, memote/suite/cli/runner.py, memote/suite/results/models.py, memote/suite/results/repo_result_manager.py, memote/suite/results/result_manager.py
=> refactor: enable compression of results

HISTORY.rst, memote/suite/collect.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_essentiality.py, memote/suite/tests/test_growth.py, setup.cfg, tests/test_for_experimental/test_for_config.py, tests/test_for_suite/test_for_results/test_for_models.py, tests/test_for_support/test_for_biomass.py, tests/test_for_utils.py, tox.ini
=> upgrade memote to be pytest 4.x compatible

memote/suite/tests/test_matrix.py
=> chore: fix display of integers by using 'raw' type

HISTORY.rst, memote/suite/cli/config.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, memote/suite/collect.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/support/consistency.py, memote/support/consistency_helpers.py, memote/utils.py, tests/test_for_support/test_for_consistency.py
Some tests were showing different results online and offline. This was due to numerical instabilities which should now be fixed.
=> WIP: Fix differences

HISTORY.rst, memote/suite/collect.py, memote/suite/tests/test_annotation.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/suite/tests/test_sbo.py, memote/suite/tests/test_thermodynamics.py
=> refactor: use a model context for every test case

HISTORY.rst, memote/suite/templates/test_config.yml
I'm making suggestions to reorganize the test cases thematically. Is this more sensible to you @phantomas1234 and @Midnighter?
=> Config reorg

HISTORY.rst, memote/suite/templates/test_config.yml, memote/suite/tests/test_matrix.py, memote/support/consistency_helpers.py, memote/support/matrix.py, tests/test_for_support/test_for_matrix.py
docs: improve test descriptions
=> fix: remove redundant test case

HISTORY.rst, memote/suite/tests/test_annotation.py, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/suite/tests/test_essentiality.py, memote/suite/tests/test_growth.py, memote/suite/tests/test_matrix.py, memote/suite/tests/test_sbo.py, memote/suite/tests/test_thermodynamics.py, memote/support/basic.py, memote/support/consistency.py, tox.ini
For each test case, I've now included a description of how that particular test is implemented. I hope that this makes it easier for a user to understand the meaning of each test without having to read the source code.
=> Implementation Details

HISTORY.rst, memote/support/helpers.py, setup.cfg, tests/test_for_support/test_for_biomass.py
=> Fix external

HISTORY.rst, memote/suite/tests/test_thermodynamics.py, memote/utils.py
=> Fix json output error reporting

HISTORY.rst, memote/support/basic.py
=> Fix unique metabolites finding

HISTORY.rst, docs/Makefile, docs/api.rst, docs/conf.py, docs/core.rst, docs/experimental.rst, docs/index.rst, docs/requirements.txt, docs/test_suite.rst
=> Fix Autodoc Generation

memote/support/biomass.py, tests/test_for_support/test_for_biomass.py
=> fix: handle a case where demand reactions already exist in a given model

memote/suite/tests/test_biomass.py, memote/support/biomass.py
=> docs: explain why C1 carriers are not considered for essential precursors

HISTORY.rst, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/suite/tests/test_matrix.py, memote/suite/tests/test_sbml.py, memote/support/basic.py, memote/support/consistency_helpers.py, memote/support/matrix.py, tests/test_for_support/test_for_basic.py
=> refactor: add metrics to all test cases

HISTORY.rst, memote/suite/tests/test_biomass.py
I previously missed one of them :angry: 
* Rename variables
=> fix: add parametrized metric

.gitignore, HISTORY.rst, memote/suite/tests/test_basic.py, memote/support/basic.py, setup.cfg, tests/test_for_support/test_for_basic.py
=> fix: change how duplicated reactions are reported

HISTORY.rst, memote/suite/tests/test_basic.py, memote/support/basic.py
Just updating the docstrings of one of the functions and the corresponding test we worked on as part of the reviewers' comments.
=> docs: update docstring and test description to reflect implementation

HISTORY.rst, docs/custom_tests.rst
I've tried drafting a set of guidelines for custom tests as per request from one of the reviewers. I'll add to this if I can think of more, but for now, let me know if you have any suggestions.
=> docs: draft guidlines for authors of custom tests

HISTORY.rst, memote/suite/cli/runner.py, setup.cfg
Fixes issue with clashing dependencies and `memote online` not working on the first try!
=> Post-release hotfix!

memote/suite/cli/reports.py
@Midnighter Let's go through the options here tomorrow. The changes that I made in the PR are what I thought the least 'invasive' while yielding the desired effect, but I do wanna talk about it with you before I proceed.
=> refactor: stay on deployment branch after generating the history report

HISTORY.rst, memote/suite/reporting/history.py, memote/support/basic.py
* Use a shorthand where `dict.setdefault` occurs.
* Fix #648
=> fix: ignore any falsy genes attribute

appveyor.yml
=> chore: use only x64 and conda

setup.cfg, src/memote/experimental/checks.py, src/memote/experimental/essentiality.py, src/memote/experimental/experimental_base.py, src/memote/experimental/medium.py, src/memote/experimental/schemata/configuration.json, src/memote/experimental/schemata/medium.json, src/memote/experimental/schemata/production.json
Pinning goodtables to version 1.0 was preventing us from using newer click versions.
=> upgrade goodtables

.github/SUPPORT.rst, README.rst
Remove the link to the mailing list. (I shut it down already.)
=> docs: remove mention of mailing list

HISTORY.rst, src/memote/support/helpers.py
=> fix: change biomass matching logic

src/memote/suite/tests/test_consistency.py, src/memote/support/consistency.py, tests/test_for_support/test_for_consistency.py, tox.ini
I didn't get around to it in time, so here are some smaller refactorings on top of #678.
=> refactor: metabolite production/consumption

HISTORY.rst, src/memote/suite/api.py, src/memote/suite/collect.py
=> feat: enable solver output on debug logging

.editorconfig, HISTORY.rst, src/memote/experimental/tabular.py, src/memote/support/helpers.py, tests/test_for_support/test_for_helpers.py
=> Fix find biomass

.coveragerc, .github/workflows/main.yml, docs/conf.py, src/memote/experimental/checks.py, src/memote/experimental/essentiality.py, src/memote/experimental/experimental_base.py, src/memote/experimental/medium.py, src/memote/suite/results/history_manager.py, tox.ini
Solve some of the problems with the new GitHub Actions workflow.
=> Fix workflow

.github/workflows/main.yml, setup.cfg, src/memote/experimental/config.py, src/memote/experimental/experimental_base.py, src/memote/suite/cli/runner.py, src/memote/suite/reporting/config.py, src/memote/suite/reporting/report.py, src/memote/suite/tests/test_basic.py, src/memote/suite/tests/test_biomass.py, src/memote/suite/tests/test_thermodynamics.py, src/memote/support/basic.py, src/memote/support/biomass.py, src/memote/support/consistency.py, src/memote/support/consistency_helpers.py, src/memote/support/helpers.py, src/memote/support/thermodynamics.py, tests/test_for_experimental/test_for_config.py, tests/test_for_suite/test_for_cli/test_for_runner.py, tox.ini
=> Remove use of importlib_resources
