opencobra/memote

memote/suite/runner.py, requirements.in, setup.py
The long tracebacks were annoying when you really just want to collect data from the tests.
=> hide tracebacks adjust to cobra version

memote/suite/reporting/bag.py, memote/suite/reporting/report.py, memote/suite/reporting/templates/basic.html, memote/suite/runner.py
The keys of the storage dict have changed and needed correction after reorganizing the package. The pytest invocation path was also adapted accordingly.
=> fix: change storage keys based on model path

MANIFEST.in
Since pytest does not use `__init__.py` files, the suite was not discovered and distributed.
=> fix: add pytest files which are not part of a package

memote/suite/reporting/report.py
Complain when the JSON storage dir is empty.
=> chore: error on empty dir

memote/suite/runner.py
Key is actually in the `dict` as `None` so have to catch that.
=> fix: catch directory argument being `None`

memote/suite/collect.py, memote/suite/runner.py
We can now run the test suite for each commit that is parent to the current branch's HEAD.
=> feat: add test suite history command

setup.py, tox.ini, tox_install.sh
`python-libsbml` takes a long time to install but should be a hard dependency
because many models require it for loading. Silent errors are then not very
helpful.
=> fix: require libsbml, update cobra

memote/suite/tests/test_basic.py, memote/support/basic.py, requirements_dev.in, setup.py, tests/conftest.py, tests/test_for_support/test_for_basic.py, tox.ini
closes #107, closes #106, closes #61, closes #67 
In this PR, I covered the remaining basic tests outlined in the [Test Catalogue](https://github.com/biosustain/memote/wiki) that don't require file IO (.gbk or similar).
As for issue #67, this PR implements the necessary functions to identify which reactions are unconstrained, irreversible, zero-constrained (lb = ub =0) and non-zero-constrained ( 0 < lb | ub < 1000), but doesn't include any tests that require a certain number/ distribution. While this information is useful when working with a model, I don't think that we need to require any fixed values here. The discussion about whether there should be tests for this or merely a listing in the report can be found here [#67](https://github.com/biosustain/memote/issues/67).
=> Basic metrics

memote/suite/tests/test_biomass.py, memote/support/biomass.py, tests/test_for_support/test_for_biomass.py
resolves #63 
So far this checks only if the Biomass reaction contains the metabolites atp_c and adp_c. I realised that looking for all the reactants of the hydrolysis reaction within the biomass metabolites might not be correct, as there are some (rare!) cases where one of them is balanced out by the same reactants contribution to the biomass. For instance, if the GAM requirement has been estimated as low (which is often the case when using the values from Neidhardt et. al.) it could happen that i.e. h2o_c that should be consumed in the hydrolysis reaction, is actually produced as a consequence of macromolecule biosynthesis.
Equally, checking for equal stoichiometry of all reactants in the hydrolysis reaction (x ATP + x H2O -> x ADP + x Pi + X H) is made more complicated when the biomass …
=> 63 check for gam

memote/suite/collect.py, memote/suite/tests/test_biomass.py
The parametrized `test_biomass` functions were broken because fixtures cannot be used directly inside of the `pytest.mark.parametrize` decorator. Instead we now inject those values into the pytest namespace such that they are available as globals. A bit ugly but seems most feasible.
=> fix: repair `test_biomass` parametrized test functions

memote/suite/tests/test_annotation.py, memote/support/annotation.py, memote/support/helpers.py, tests/test_for_support/test_for_annotation.py
resolves #33 
This PR includes a couple of new checks and tests.
First of all when I refer to 'items' I mean either metabolites or reactions.
1. I am adding `annotation.py`, which contains:
`REACTION_ANNOTATIONS` : A dictionary mapping MIRIAM-style reaction database namespaces against the corresponding identifier patterns as compiled regex patterns.
METABOLITE_ANNOTATIONS` : A dictionary mapping MIRIAM-style metabolite database namespaces against the corresponding identifier patterns as compiled regex patterns.
I selected the included databases more or less from experience, i.e. what I had seen to be commonly referenced in metabolic models. I am open for input on what are or aren't 'must-have' databases.
In addition to these two dictionaries, `annotation.py` contains functions to list …
=> 33 annotation tests

memote/suite/tests/test_syntax.py, memote/support/helpers.py, memote/support/syntax.py, tests/test_for_support/test_for_syntax.py
resolves #116
Straight forward fix again. Concerns the modules syntax, test_for_syntax and test_syntax. Adds the reverse case of #102 checking that DM, SK, and EX-labeled reactions are indeed demand, sink and exchange reactions.
=> Reverse boundary check

memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
resolves #104 
This PR tackles the identification and testing for reactions that participate in stoichiometrically balanced cycles (SBCs) or also referred to as Type III pathways. What I implemented is nominal FVA with the default objective and default bounds, followed by loopless FVA (the fast variant using the CycleFreeFlux algorithm in cobrapy). I then list all reactions that show a different flux distribution.
My initial approach, the one described in #104 doesn't work as the FVA solution with closed bounds becomes infeasible with models that have a defined (fast constrained) NGAM requirement.
The changes only affect the models involving functions from consistency.py
=> Type III loops or Stoichiometrically Balanced Cycles

memote/suite/tests/test_biomass.py
The pytest fixture `model` creates a model copy whereas the parametrized biomass
reactions correspond to the original model. We thus need to retrieve the
new reaction from the model copy.
=> fix: retrieve reaction from model copy

memote/suite/collect.py, memote/suite/runner.py, memote/suite/tests/test_consistency.py, tox.ini
* Was more trouble than gain.
* Correct function signature for `test_find_stoichiometrically_balanced_cycles`.
* Use single line tracebacks for command line mode of memote.
* Make missing Python interpreter error.
=> fix: remove dummy dict

memote/suite/runner.py
`memote new` now acccepts a `--replay`` option that will create a repository from the template with the exact answers as before. Should make playing with this feature a little more convenient.
=> feat: add a replay option

memote/support/basic.py, memote/support/consistency.py, memote/support/consistency_helpers.py, memote/support/helpers.py, memote/support/syntax.py
=> Numpydoc style docstrings

HISTORY.rst, memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
=> refactor: disable test for cycles temporarily

HISTORY.rst, memote/suite/tests/test_syntax.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
=> fix: catch errors where they have been reported

HISTORY.rst, memote/suite/api.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py
We make the command line output of pytest more verbose until the report
output is more informative and nicely presented.
=> refactor: make pytest more verbose

HISTORY.rst, memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
In this PR I implemented the method of finding erroneous energy-generating cycles published by [1]. I've extended the list of covered energy metabolites by 2 menaquinol present in the BiGG database (menaquinol 6 and 7). 
- [1] Fritzemeier, C. J., Hartleb, D., Szappanos, B., Papp, B., & Lercher, M. J. (2017). Erroneous energy-generating cycles in published genome scale metabolic networks: Identification and removal. PLoS Computational Biology, 13(4), 1–14. http://doi.org/10.1371/journal.pcbi.1005494
=> Test for EGC

HISTORY.rst, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
=> fix: account for reversibility

HISTORY.rst, README.rst
=> fix: swap all links to rtd/stable with rtd/latest

HISTORY.rst, memote/utils.py, tests/conftest.py, tests/test_for_suite/test_for_api.py, tests/test_for_suite/test_for_cli/test_for_callbacks.py, tests/test_for_suite/test_for_cli/test_for_runner.py, tests/test_for_support/test_for_annotation.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_biomass.py, tests/test_for_support/test_for_consistency.py, tests/test_for_support/test_for_helpers.py, tests/test_for_support/test_for_syntax.py
Functions that create models in the `test_for*` pytest modules should now be decorated with `@register_with(MODEL_REGISTRY)` rather than made known in the `model_builder` function.
=> refactor: use a decorator instead of model builder

HISTORY.rst, MANIFEST.in, memote/suite/api.py, memote/suite/cli/config.py, memote/suite/cli/runner.py, memote/suite/collect.py, memote/suite/test_config.yml
* Test cases and modules can be run exclusively with `--exclusive <name>`. This option can be passed multiple times or configured.
* Test cases and modules can be skipped with `--skip <name>`. This option can be passed multiple times or configured.
* Introduces a dummy configuration for test grouping and weighing. This is directly inserted into the result JSON.
* Re-organizes the resulting JSON a bit.
=> feat: add exclusive testing, skipping, and config

memote/version_info.py
=> fix: include memote in the version info

.travis.yml, setup.py
Unfortunate dependency mess. Just like pandas we remove 3.4 from our automatic test pipeline.
=> fix: drop support for Python 3.4 just like pandas

memote/suite/api.py, memote/suite/cli/config.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, setup.py
A different solver can now be specified with `memote run --solver <solver name> <model>`
=> feat: add solver configuration

HISTORY.rst, docs/custom_tests.rst, docs/getting_started.rst, docs/index.rst, memote/suite/api.py, memote/suite/cli/reports.py, memote/suite/cli/runner.py, memote/suite/collect.py, memote/utils.py, tests/test_for_utils.py
Expanded the memote CLI with the option `--custom` which requires the user to provide a tuple containing an absolute path to a custom test directory and the absolute path to a custom config file.
I provided documentation for this approach aswell as making it clear how to provide merely one or many custom test directories (without requiring a config file) in the form of pytest arguments.
=> Allow users to provide a custom pytest directory for test discovery

HISTORY.rst, memote/suite/tests/test_basic.py, memote/suite/tests/test_biomass.py, memote/suite/tests/test_consistency.py, memote/support/basic.py, memote/support/biomass.py, memote/support/consistency.py, memote/support/helpers.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_biomass.py, tests/test_for_support/test_for_consistency.py
* Implement a test for unbounded flux through reactions in the default
condition.
* Implement a test for detecting metabolites that can either be produced or
removed from the model when all system boundaries are closed.
* Implement a test for 'direct' metabolites, i.e. the detection of biomass
precursors that are not involved in any metabolic reactions; only in
exchange reactions, transporters and the biomass reaction itself.
* Implement a test that checks for a low ratio of transport reactions without
GPR relative to the total amount of transport reactions.
=> Additional tests - Implements a bunch of requested tests.

HISTORY.rst, memote/suite/tests/test_sbo.py
Add try/except structure to `ann["metric"]` in `test_sink_specific_sbo_presence` to prevent ZeroDivisionError when no sink reactions are present. pytest skips this test instead.
=> fix/sbo: prevent divide by zero error

HISTORY.rst, memote/suite/tests/test_basic.py
Changed assert statement from comparing the length of `ann["metric"]` to just comparing ann["metric"] itself, preventing a type error (as floats don't have a length)
=> fix/basic: fix string-float type error in assert statement

.github/CONTRIBUTING.rst, HISTORY.rst
sphinx` linkcheck is reporting the following errors:
```
preparing documents... done
writing output... [  2%] _autogen/memote
writing output... [  5%] _autogen/memote.suite
writing output... [  8%] _autogen/memote.suite.api
writing output... [ 10%] _autogen/memote.suite.cli
writing output... [ 13%] _autogen/memote.suite.cli.callbacks
writing output... [ 16%] _autogen/memote.suite.cli.config
writing output... [ 18%] _autogen/memote.suite.cli.reports
writing output... [ 21%] _autogen/memote.suite.cli.runner
writing output... [ 24%] _autogen/memote.suite.collect
writing output... [ 27%] _autogen/memote.suite.reporting
writing output... [ 29%] _autogen/memote.suite.reporting.bag
writing output... [ 32%] _autogen/memote.suite.reporting.diff
writing output... [ 35%] …
```
=> fix: replace broken link in contributing.rst

HISTORY.rst, memote/suite/api.py, memote/suite/reporting/snapshot.py
This PR implements @jonovik 's proposal to fix UnicodeDecodeErrors that we see locally on win 10 and macOS Sierra.
=> fix: unicode decode errors

memote/support/consistency.py
* `find_metabolites_produced_with_closed_bounds`
* `find_metabolites_consumed_with_closed_bounds`
These two functions were returning a list of metabolite ids, not metabolite objects. To keep memote functions consistent, these functions now return a list of metabolite objects, not string ids, as previously discussed with Moritz and Christian. An entry to `History.rst` will be added after #350 is pulled so as to not create unnecessary merge conflicts within `History.rst`
=> fix: functions return objects not str ids

HISTORY.rst, memote/suite/test_config.yml, memote/suite/tests/test_matrix.py, memote/support/matrix.py
These changes should address the concerns in issue #233 except for adding in/testing for a list of parallel routes. Additionally, the number of independent conserved metabolite relations, i.e. conservation pools, is added but the actual pools themselves are not shown as the left-nullspace of large network reconstructions is extremely difficult to interpret.
=> Matrix tests

Makefile, docs/Makefile, docs/conf.py
* The widely spread recipe for building apidoc automatically seems to
mess up Sphinx 1.7, however, it seems to just work without it? Leaving
it in commented for now.
* Make slight adjustments to the Makefiles.
=> fix: comment `run_apidoc`

memote/utils.py
`get_ids_and_bounds` used to return a list of tuples, which caused errors with the `truncate` function in `util.py`. It has been fixed to return a list of str, removing the `TypeError` exceptions being raised when running `memote run`
=> fix: get_ids_and_bounds now returns list of str

memote/suite/tests/test_basic.py
"model to be named" is ambiguous and implies that the SBML `name` attribute should be set on the model.
By clearly stating that the model should be identified via ID this is clearer.
=> Clarified model id test

memote/suite/tests/test_basic.py, memote/support/helpers.py
You are doing `>=1` tests but wrote `more than one`, this is incorrect.
Change to "at least one" or "more than zero".
=> Clarified wording on genes, species and reactions test

memote/suite/api.py, memote/suite/cli/reports.py, memote/suite/reporting/history.py
=> fix: remove unused 'index' and 'filename' parameters from History object

setup.cfg
Pinned the cobrapy version to 0.12.0 since the new release (0.12.1/ 0.13.0) cause breaking changes, which would require a larger refactor.
Opened #445 to keep track of this issue.
=> fix: pin cobra version to latest stable

memote/__init__.py, memote/jinja2_extension.py
We need a jinja2 extension here in order to create some path conversion for the memote cookiecutter. Since the cookiecutter should be invoked by `memote new`, I thought it best to add the dependency here as it is guaranteed to be installed.
=> feat: create an extension for the cookiecutter

HISTORY.rst, memote/suite/cli/runner.py, memote/suite/results/history_manager.py, memote/suite/results/repo_result_manager.py
`memote history` now skips commits that didn't modify the model file. Users can choose to overwrite existing results or not.
=> refactor: selectively compute history

HISTORY.rst, memote/suite/cli/runner.py, memote/suite/results/history_manager.py, memote/support/basic.py, memote/support/helpers.py, memote/utils.py, setup.cfg, tests/test_for_suite/test_for_cli/conftest.py, tests/test_for_suite/test_for_cli/test_for_runner.py
changed, but implement a flag that enables testing nonetheless. The flag is 
``--test-unchanged``.
=> Ignore commits in which the model was not changed with `memote run`, add option to trigger a test.

HISTORY.rst
Fixing the faux-pas Ben describes here:
https://github.com/opencobra/memote/pull/508#commitcomment-31125337
=> chore: correct mistake in history.rst about the skip-unchanged flag

HISTORY.rst, memote/suite/tests/test_consistency.py, memote/support/consistency.py, tests/test_for_support/test_for_consistency.py
=> fix: rely on cobrapy's find_blocked_reactions

HISTORY.rst, memote/suite/templates/test_config.yml, memote/suite/tests/test_thermodynamics.py, memote/support/thermodynamics.py, tests/test_for_support/test_for_thermodynamics.py
=> Refactor thermo

HISTORY.rst, memote/support/annotation.py, tests/test_for_support/test_for_annotation.py
I've left out SMILES for now because there seems to be no dedicated registry for it on `identifiers.org` and hence no MIRIAM-compliant identifier pattern.
@matthiaskoenig do you have any suggestions on how to still include SMILES or do you think InChI will suffice?
=> feat: extend annotation tests with a check for inchi strings

HISTORY.rst, memote/suite/tests/test_basic.py, memote/suite/tests/test_consistency.py, memote/support/consistency.py, memote/support/helpers.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_consistency.py, tests/test_for_support/test_for_helpers.py
Metabolites with irreversible exchange reactions were falsely identified as orphans. Not consumed and not produced metabolites were detected opening all boundary reactions. This has changed to only opening exchanges.
* Orphans are now a complete subset of not produced compounds.
* Dead-ends are now a complete subset of not consumed compounds.
=> Fix topology tests

HISTORY.rst, memote/suite/tests/test_biomass.py
The reason for the odd value was inverted logic in the test function.
=> fix: invert logic of test_fast_growth_default

docs/conf.py, docs/requirements.txt
The AutoAPI part worked so now in our docs we have a [beautiful, automatically generated API documentation](https://memote.readthedocs.io/en/latest/autoapi/index.html) appended to the end of our ToC tree, but the autodoc part still didn't build. I investigated this in the RTD logs and saw that two packages could not be imported in their build process (`pylru` and `equilibrator_api`). I've added them to the `requirements.txt`.
Hopefully, RTD will be able to build the dedicated test section with sphinx_autodoc now.
=> fix: add packages needed by sphinx autodoc to rtd build environment

tests/test_for_support/test_for_validation.py
Change due to redesign in cobrapy. This will have to be reverted in
future.
=> test: temporarily do not expect warnings

HISTORY.rst, src/memote/suite/collect.py
This removes the warnings that appear with the most recent version of Pytest under Python 3.6.0 by registering the custom markers we use for parametrization (`biomass`, `essentiality` and `growth`). 
Running `memote report snapshot` on Google Colaboratory (Python 3.6.8) errors with something along these lines:
```'biomass' not found in `markers` configuration option```
This is [recommended by the authors of pytest](https://docs.pytest.org/en/latest/example/markers.html?highlight=register%20markers#registering-markers)
=> chore: register custom pytest markers to snuff error messages

scripts/update_mock_repo.py, src/memote/suite/cli/runner.py, src/memote/utils.py, tests/test_for_suite/test_for_cli/test_for_runner.py, tests/test_for_utils.py
`memote history` will fail on a commit that deleted the model file.
```
Running the test suite for commit '8daf...'.
Traceback (most recent call last):
...
File "C:\NMBU\Miniconda3\envs\cbm\lib\site-packages\click\core.py", line 535, in invoke
return callback(*args, **kwargs)
File "c:\git\digisal\memote\memote\suite\cli\runner.py", line 393, in history
blob = cmt.tree[model]
File "C:\NMBU\Miniconda3\envs\cbm\lib\site-packages\git\objects\tree.py", line 298, in __getitem__
return self.join(item)
File "C:\NMBU\Miniconda3\envs\cbm\lib\site-packages\git\objects\tree.py", line 225, in join
item = tree[token]
File "C:\NMBU\Miniconda3\envs\cbm\lib\site-packages\git\objects\tree.py", line 298, in __getitem__
return self.join(item)
File "C:\NMBU\Miniconda3\envs\cbm\lib\site-packages\git\objects\tre …
```
=> Have memote.utils.is_modified() return False if file was deleted.

HISTORY.rst, src/memote/support/consistency.py
In order to speed up the consistency tests of checking metabolite production and consumption with open bounds, the logic of the test has been changed. Instead of adding a boundary to the model each time, the test now works by sequentially changing the linear coefficients of the metabolites, which should be faster.
* Add a variable **just once** (bounds in 0,1000);
* Set the variable as the objective of the model;
* for each metabolite:  
▪ get the linear coefficients of the constraint of each metabolite;  
▪ add a coefficient to the variable in the constraint (-1 for production and 1 for consumption)
▪ solve;  
▪ restore constraint;  
▪ If not solution, add the metabolite to the returned output.
**Multiprocessing** was also added to decrease the running time.
=> fix: change logic of test production and consumption metabolites to speed up the process

HISTORY.rst, docs/experimental_data.rst, src/memote/experimental/config.py, src/memote/experimental/essentiality.py, src/memote/experimental/experiment.py, src/memote/experimental/experimental_base.py, src/memote/experimental/growth.py, src/memote/experimental/schemata/configuration.json, tests/test_for_experimental/data/growth.yml, tests/test_for_experimental/test_for_experimental_base.py
The growth tests with experimental data do not work when, after applying the medium, the solver returns infeasible, propagating a `NaN` to the growth comparison that hampers the tests (reports 0 for all metabolites).
Now the user can provide an absolute value in the `experiments.yml` configuration as minimum growth that acts both on essentiality and growth experiments. If no value is provided, it defaults to a coefficient (set as 10% for now) of the growth under default constraints.
=> fix: set threshold to model tolerance when solution is infeasible

HISTORY.rst, src/memote/suite/tests/test_consistency.py, src/memote/support/consistency.py, src/memote/support/consistency_helpers.py, src/memote/support/matrix.py, tests/test_for_support/test_for_consistency.py
The detection of minimal uncoservable sets was not complying with experimental results.
**There was a constraint lacking in the MILP problem (y>=0)**. Moreover, the nullspace computation was verified with the sympy interface, which, by default, normalizes the nullspace yielding the same results as in the toy examples in [Gevorgyan et al., 2008](https://academic.oup.com/bioinformatics/article/24/19/2245/248822). This behavior is due to the definition of "zero". It yields the same minimal unconservable sets as the numpy implementation so it was left as it was.
=> fix: detect minimal uncoservable sets

HISTORY.rst, src/memote/experimental/config.py, src/memote/experimental/essentiality.py, tests/test_for_suite/test_for_api.py, tests/test_for_suite/test_for_reporting/test_for_history.py, tests/test_for_support/test_for_basic.py, tests/test_for_support/test_for_biomass.py, tests/test_for_support/test_for_consistency.py, tests/test_for_support/test_for_helpers.py
`pytest` is failing because an essentially test is extracting the wrong information from [`cobra.flux_analysis.single_cell_deletion`](https://github.com/opencobra/cobrapy/blob/d9d3bf99198ee0a93346bd860fce4cf217297937/src/cobra/flux_analysis/deletion.py#L236), whose behavior has recently changed. 
Change index to column access. An if statement was added to the list comprehension because it made the error more clear, but feel free to remove it.
=> fix: point to ids column instead of index

.github/workflows/main.yml, HISTORY.rst, docs/getting_started.rst, setup.cfg, src/memote/suite/cli/callbacks.py, src/memote/suite/cli/runner.py, tests/test_for_suite/test_for_cli/test_for_runner.py
This is accompanied with a [PR to cookiecutter-memote](https://github.com/opencobra/cookiecutter-memote/pull/21). 
Github changed the API for authentication (see [deprecation notice](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/)):
* Username+password authentication is no longer possible, it has to be done via a token. The [web application flow](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow) may be relevant for memote.
* The authorization endpoint does not exist anymore.
Thus, the command line option `memote online` has to be updated accordingly.
For the reasons outlined above, it is easier to replace travis with github actions than to figure out the new workflow; the difficulty lies in …
=> Replace travis with github actions

src/memote/suite/tests/test_consistency.py
=> Cycles met ids

HISTORY.rst, src/memote/suite/cli/reports.py, src/memote/suite/cli/runner.py
Setting the solver backend before creating a model saves time (the model doesn't have to be recreated), and has other advantages, too.
=> feat: allow setting solver backend early
